### PR TITLE
Export date select

### PR DESCRIPTION
**Pull request by mt-neus**
new icon for date selection on exports:

Screen Shot 2019-07-23 at 12 02 18

### CODE REVIEW

**Comment by mt-micky** [comment]
I don’t mind merging but whoever decided to add icons need to make sure to look at existing ones.
Did we pass the 300s icon yet?

**Comment by mt-micky** [comment]
@mt-neus make sure to bump version after making a change

**Comment by mt-neus** [comment]
> I don’t mind merging but whoever decided to add icons need to make sure to look at existing ones.
> Did we pass the 300s icon yet?

I will try to clean it... but it might take time. Duplicated icons have different names, and I don't know the whole impact that it has. Which projects use this as fonts? I know mt-web-modules, mt-web-client and mt-web-link

**Comment by mt-neus** [comment]
> @mt-neus make sure to bump version after making a change

I did't too soon >.<

**Review by mt-micky — APPROVED** [review]

**Pull request merged**
